### ISSUE TITLE
Problem with imencode

### ISSUE THREAD

**Issue by GonzaloMHM** [gidesa/ocvWrapper46#18]
Hello again, I'm trying to save the output image to memory instead of a file, but I get violation error:

```
var
  params:    PCvvector_int;
  buf: PCvVector_uchar;
...
  pCvMatConvertTo(colorImg, colorImg, CV_8U, 255);   
  cvstr.pstr:= '.jpg';    
  params:= pCvVectorintCreate(2);
  pCvVectorIntSet(params, 0, 100);    
  pCvVectorIntSet(params, 0, Integer(IMWRITE_JPEG_QUALITY));  
  pcvImEncode(@cvstr, colorImg, buf, params);
```

Maybe I have to initialize buf any way? Or params is bad initialized? (swapping the two params is not helping, although maybe it must be done). Thanks for any help.
Just written this I've realized that both vector sets were with '0' as second argument, but replacing the second one with '1' doesn't help neither.

**Comment by gidesa** [comment]
Hello,
the pCvVectorIntSet must be in this order:  

```
  pCvVectorIntSet(params, 0, Integer(IMWRITE_JPEG_QUALITY));
  pCvVectorIntSet(params, 1, 100);

```
that is, first the parameter id, then the parameter value.
See https://docs.opencv.org/4.6.0/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce
   
But, more important, the buf vector must be created before the call:
`  buf:=pCvVectorucharCreate(0);`
Because Opencv functions require that class parameters are always defined from caller, although empty when they are output parms, as in this case.
It's the function that internally redims and fills the output vector.

**Comment by GonzaloMHM** [comment]
A lot of thanks, yes I forgot that C++ constructs objects just by declaring them unless Delphi that must be constructed with the constructor. Thank you very much again for this useful code.
